### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement pkg-resources==0.0.0 

### ISSUE THREAD

**Issue by sdwvit** [7rouz/youtube-playlist-creator#5]
Hey! I appreciate the package and I don't have any hope of you updating it, but there is a broken dependency which may be easy to fix.
```
ERROR: Could not find a version that satisfies the requirement pkg-resources==0.0.0 
```

**Comment by 7rouz** [comment]
hi !
I am glad that you find the project useful. I will take a look at the issue and get back to you.

**Comment by 7rouz** [comment]
@sdwvit 
the fix is temporarly on a new branche [oauth2-issue](https://github.com/7rouz/youtube-playlist-creator/tree/oauth2-issue). 
It took more time than expected due to OAuth that was no longer working :smiley: 
It should work fine, but I have to update Readme before merging it with master branche.
please let me know if it still doesn't work for you.

**Comment by 7rouz** [comment]
Hi @sdwvit !
issue resolved !
please let me know if it still doesn't work for you.
